### ISSUE TITLE
ImportError: No module named google_translate_py

### ISSUE THREAD

**Issue by Tizioincognit0** [gunesmes/subtitle_translator#11]
When I’m trying to translate some subtitle files in the folder "test", I’m getting the following errors even if I installed all requirements. I'm using subtitle_translator on macOS Ventura 13.4.
```
user@MacBook-Pro subtitle_translator % python run.py ~/Documents/Software/Git/subtitle_translator/test 10000 google en it
 - - - - Translating: {file} - - - - - -
Traceback (most recent call last):
  File "run.py", line 79, in <module>
    translater(sys.argv[1:])
  File "run.py", line 73, in translater
    s.translate_subtitle_raw(subFile, source_language, target_language, translator, max_length)
  File "~/Documents/Software/Git/subtitle_translator/subtitle_translater.py", line 283, in translate_subtitle_raw
    from google_translate_py import Translator
ImportError: No module named google_translate_py

```

**Comment by gunesmes** [comment]
@Tizioincognit0 just need to install the requirements, please check the README

```
# Go to project path
cd /path/to/subtitle_translator

# install the reqirements
pip install -r requirements.txt
```

**Comment by Tizioincognit0** [comment]
> @Tizioincognit0 just need to install the requirements, please check the README
> 
> ```
> # Go to project path
> cd /path/to/subtitle_translator
> 
> # install the reqirements
> pip install -r requirements.txt
> ```

It gives me the following error.
`user@MacBook-Pro downloads % pip install -r ~/Documents/Software/Git/subtitle_translator/requirements.txt
Defaulting to user installation because normal site-packages is not writeable
Collecting certifi==2022.12.7
  Using cached certifi-2022.12.7-py3-none-any.whl (155 kB)
ERROR: Could not find a version that satisfies the requirement charset-normalizer==3.1.0 (from versions: 0.1a0, 0.1.1a0, 0.1.2b0, 0.1.4b0, 0.1.5b0, 0.1.7, 0.1.8, 0.2.0, 0.2.1, 0.2.2, 0.2.3, 0.3.0, 1.0.0, 1.1.0, 1.1.1, 1.2.0, 1.3.0, 1.3.1, 1.3.2, 1.3.3, 1.3.4, 1.3.5, 1.3.6, 1.3.7, 1.3.8, 1.3.9, 1.4.0, 1.4.1, 2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.0.4, 2.0.5, 2.0.6, 2.0.7, 2.0.8, 2.0.9, 2.0.10, 2.0.11, 2.0.12, 2.1.0, 2.1.1, 3.0.0b1, 3.0.0b2, 3.0.0rc1, 3.0.0, 3.0.1)
ERROR: No matching distribution found for charset-normalizer==3.1.0
`

**Comment by gunesmes** [comment]
looks like your local is not updated, please do update

`git pull`

**Comment by Tizioincognit0** [comment]
> looks like your local is not updated, please do update
> 
> `git pull`

I've did it and now it gives me the following error.
`user@MacBook-Pro downloads % pip install -r ~/Documents/Software/Git/subtitle_translator/requirements.txt  
Defaulting to user installation because normal site-packages is not writeable
Collecting googletranslate_python==1.0.3
  Using cached googletranslate_python-1.0.3-py3-none-any.whl (5.2 kB)
ERROR: Could not find a version that satisfies the requirement Requests==2.31.0 (from versions: 0.2.0, 0.2.1, 0.2.2, 0.2.3, 0.2.4, 0.3.0, 0.3.1, 0.3.2, 0.3.3, 0.3.4, 0.4.0, 0.4.1, 0.5.0, 0.5.1, 0.6.0, 0.6.1, 0.6.2, 0.6.3, 0.6.4, 0.6.5, 0.6.6, 0.7.0, 0.7.1, 0.7.2, 0.7.3, 0.7.4, 0.7.5, 0.7.6, 0.8.0, 0.8.1, 0.8.2, 0.8.3, 0.8.4, 0.8.5, 0.8.6, 0.8.7, 0.8.8, 0.8.9, 0.9.0, 0.9.1, 0.9.2, 0.9.3, 0.10.0, 0.10.1, 0.10.2, 0.10.3, 0.10.4, 0.10.6, 0.10.7, 0.10.8, 0.11.1, 0.11.2, 0.12.0, 0.12.1, 0.13.0, 0.13.1, 0.13.2, 0.13.3, 0.13.4, 0.13.5, 0.13.6, 0.13.7, 0.13.8, 0.13.9, 0.14.0, 0.14.1, 0.14.2, 1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.1.0, 1.2.0, 1.2.1, 1.2.2, 1.2.3, 2.0.0, 2.0.1, 2.1.0, 2.2.0, 2.2.1, 2.3.0, 2.4.0, 2.4.1, 2.4.2, 2.4.3, 2.5.0, 2.5.1, 2.5.2, 2.5.3, 2.6.0, 2.6.1, 2.6.2, 2.7.0, 2.8.0, 2.8.1, 2.9.0, 2.9.1, 2.9.2, 2.10.0, 2.11.0, 2.11.1, 2.12.0, 2.12.1, 2.12.2, 2.12.3, 2.12.4, 2.12.5, 2.13.0, 2.14.0, 2.14.1, 2.14.2, 2.15.1, 2.16.0, 2.16.1, 2.16.2, 2.16.3, 2.16.4, 2.16.5, 2.17.0, 2.17.1, 2.17.2, 2.17.3, 2.18.0, 2.18.1, 2.18.2, 2.18.3, 2.18.4, 2.19.0, 2.19.1, 2.20.0, 2.20.1, 2.21.0, 2.22.0, 2.23.0, 2.24.0, 2.25.0, 2.25.1, 2.26.0, 2.27.0, 2.27.1)
ERROR: No matching distribution found for Requests==2.31.0`

**Comment by gunesmes** [comment]
looks like your python installation is old or not supported some libs. what is your python version, 

`python --version`

also try with pip3

`pip3 install -r requirements.txt`

**Comment by Tizioincognit0** [comment]
> also try with pip3
> 
> `pip3 install -r requirements.txt`

I was able to install dependencies with pip3 but now I'm getting the following error when I'm trying to translate test subtitles.
`user@MacBook-Pro downloads % python3 ~/Documents/Software/Git/subtitle_translator/run.py ~/Documents/Software/Git/subtitle_translator/test 10000 google en it  
Traceback (most recent call last):
  File "~/Documents/Software/Git/subtitle_translator/run.py", line 13, in <module>
    from subtitle_translater import SubsTranslater
ImportError: bad magic number in 'subtitle_translater': b'\x03\xf3\r\n'
`

**Comment by gunesmes** [comment]
It looks like Unix system problem, may be this solves it
https://stackoverflow.com/a/514395

**Comment by Tizioincognit0** [comment]
> It looks like Unix system problem, may be this solves it
> [stackoverflow.com/a/514395](https://stackoverflow.com/a/514395)

It fixed "bad magic number error" but I'm still getting this error.
`user@MacBook-Pro downloads % python3 ~/Documents/Software/Git/subtitle_translator/run.py ~/Documents/Software/Git/subtitle_translator/test 10000 google en it
Traceback (most recent call last):
  File "~/Documents/Software/Git/subtitle_translator/run.py", line 13, in <module>
    from subtitle_translater import SubsTranslater
ModuleNotFoundError: No module named 'subtitle_translater'
`

**Comment by gunesmes** [comment]
I think you should run it inside the project path. I will convert it to a cli toll soon.

**Comment by Tizioincognit0** [comment]
> I think you should run it inside the project path. I will convert it to a cli toll soon.

Thank you. I did it and now it works flawlessly.

**Comment by gunesmes** [comment]
Hope you give a star.
