### ISSUE TITLE
Wrong module name imported

### ISSUE THREAD

**Issue by karim23657** [gunesmes/subtitle_translator#12]
I got this error:
```shell
~ ts
Traceback (most recent call last):
  File "/usr/local/bin/ts", line 5, in <module>
    from transitle.__main__ import main
  File "/usr/local/lib/python3.10/dist-packages/transitle/__init__.py", line 1, in <module>
    from .ts import TranslateSubtitle
  File "/usr/local/lib/python3.10/dist-packages/transitle/ts.py", line 12, in <module>
    from googletranslatepy import Translator
ModuleNotFoundError: No module named 'googletranslatepy'
```

I thing you should replace `from googletranslatepy import Translator` with `from googletrans import Translator` if you installed `pip install googletrans`

**Comment by gunesmes** [comment]
@karim23657  thanks for reporting. install_requires in set_up doesn't include all the required libs so it was not working if you don't have those. Fixed and updated the `ts` package so please uninstall and install to test it.

**Comment by gunesmes** [comment]
issue should have gone so closing this
