### ISSUE TITLE
Error from Goslate.py

### ISSUE THREAD

**Issue by john65537** [gunesmes/subtitle_translator#2]
Couldn't work in ubuntu, error: 
  File "src/goslate.py", line 208, in _basic_translate
    translation = u''.join(i['trans'] for i in data['sentences'])
TypeError: string indices must be integers
Any suggestion?

**Comment by gunesmes** [comment]
seems like Google is blocking for the IP block you have is sending block requests. I got this error either. You can use Yandex, it is still working.

`Our systems have detected unusual traffic from your computer network. Please try your request again later. Why did this happen?`

**Comment by Tizioincognit0** [comment]
I’m having a different error when I’m translating with Google Translate. Could the cause be the same?
````
python2.7 run.py ~/Downloads/subtitle_translator/ 100 google ar it
Traceback (most recent call last):
  File "run.py", line 9, in <module>
    from subTranslater import SubsTranslater
  File "src/subTranslater.py", line 7, in <module>
    import time, requests, codecs, sys
ImportError: No module named requests

**Comment by gunesmes** [comment]
you should install `requests` library by `pip install requests`
