### ISSUE TITLE
Additional charcters 

### ISSUE THREAD

**Issue by shadyslim2018** [gunesmes/subtitle_translator#6]
I can see the output in the terminal
```
90
00:15:00,413 --> 00:15:05,369
كان يتحدث بثقة هكذا.
He was speaking confidently like that.
```
But srt output added few more characters

```
90
00:15:00,413 --> 00:15:05,369
b'He was speaking confidently like that.'
```
So it removed the Arabic writing, which is fine, but then it added a **b** and quotation marks **' '**

**Comment by gunesmes** [comment]
This should be fixed
