### ISSUE TITLE
improper encoding when writing srt file

### ISSUE THREAD

**Issue by Yoshi8765** [gunesmes/subtitle_translator#7]
Hi, cool program and thanks for making it!
I'm having a problem where I'm using it to go from `en` to `ja` (english to Japanese) and getting a proper output, except the encoding is all messed up. The output ends up being embedded hexadecimal rather than proper Japanese characters in UTF-8.
For example, one line is
`CJ\xe3\x82\xa8\xe3\x83\xb3\xe3\x82\xbf\xe3\x83\xbc\xe3\x83\x86\xe3\x82\xa4\xe3\x83\xb3\xe3\x83\xa1\xe3\x83\xb3\xe3\x83\x88\xe3\x81\xa8\xe3\x83\x87\xe3\x82\xaf\xe3\x82\xb9\xe3\x82\xbf\xe3\x83\xbc\xe3\x83\xbb\xe3\x82\xb9\xe3\x82\xbf\xe3\x82\xb8\xe3\x82\xaa\xe3\x81\x8c\xe5\x8f\x82\xe5\x8a\xa0`
instead of
`CJエンターテインメントとデクスター・スタジオが参加`

I haven't been able to find a bulk decoder tool to deal with this. I know a bit of python but don't really know how to deal with this. I also looked into `subtitle_translater.py` and it seems like UTF-8 encoding is implemented, so maybe this is a bug?

**Comment by gunesmes** [comment]
Fixed this

```
➜  subtitle_translator git:(master) ✗ python run.py . 40 google pl ja
['.', '40', 'google', 'pl', 'ja']
1
00:00:40,983 --> 00:00:50,983
English. Subtitles. The Alien.
英語。

2
00:00:56,388 --> 00:00:57,889
I don't know what the fuck is going on,
何が起こっているのかわからない

3
00:00:57,891 --> 00:00:59,657
in this country, man!
この国で、男！

4
00:00:59,659 --> 00:01:01,993
CJ Entertainment and Dexter Studios Participate
CJエンターテインメントとデクスタースタジオが参加
```
